#pragma once
typedef struct ccn_node ccn_node;
struct ccn_node *PRTbool(struct ccn_node *node);
struct ccn_node *PRTfloat(struct ccn_node *node);
struct ccn_node *PRTnum(struct ccn_node *node);
struct ccn_node *PRTvar(struct ccn_node *node);
struct ccn_node *PRTvarlet(struct ccn_node *node);
struct ccn_node *PRTmonop(struct ccn_node *node);
struct ccn_node *PRTbinop(struct ccn_node *node);
struct ccn_node *PRTassign(struct ccn_node *node);
struct ccn_node *PRTstmts(struct ccn_node *node);
struct ccn_node *PRTvardecl(struct ccn_node *node);
struct ccn_node *PRTparam(struct ccn_node *node);
struct ccn_node *PRTglobdef(struct ccn_node *node);
struct ccn_node *PRTglobdecl(struct ccn_node *node);
struct ccn_node *PRTfor(struct ccn_node *node);
struct ccn_node *PRTdowhile(struct ccn_node *node);
struct ccn_node *PRTwhile(struct ccn_node *node);
struct ccn_node *PRTifelse(struct ccn_node *node);
struct ccn_node *PRTfunbody(struct ccn_node *node);
struct ccn_node *PRTfundef(struct ccn_node *node);
struct ccn_node *PRTfundefs(struct ccn_node *node);
struct ccn_node *PRTcast(struct ccn_node *node);
struct ccn_node *PRTfuncall(struct ccn_node *node);
struct ccn_node *PRTreturn(struct ccn_node *node);
struct ccn_node *PRTexprstmt(struct ccn_node *node);
struct ccn_node *PRTids(struct ccn_node *node);
struct ccn_node *PRTarrexpr(struct ccn_node *node);
struct ccn_node *PRTexprs(struct ccn_node *node);
struct ccn_node *PRTdecls(struct ccn_node *node);
struct ccn_node *PRTprogram(struct ccn_node *node);
ccn_node *SPdoScanParse(ccn_node *);
ccn_node *CPYbool(ccn_node *);
ccn_node *DELbool(ccn_node *);
ccn_node *CHKbool(ccn_node *);
ccn_node *CPYfloat(ccn_node *);
ccn_node *DELfloat(ccn_node *);
ccn_node *CHKfloat(ccn_node *);
ccn_node *CPYnum(ccn_node *);
ccn_node *DELnum(ccn_node *);
ccn_node *CHKnum(ccn_node *);
ccn_node *CPYvar(ccn_node *);
ccn_node *DELvar(ccn_node *);
ccn_node *CHKvar(ccn_node *);
ccn_node *CPYvarlet(ccn_node *);
ccn_node *DELvarlet(ccn_node *);
ccn_node *CHKvarlet(ccn_node *);
ccn_node *CPYmonop(ccn_node *);
ccn_node *DELmonop(ccn_node *);
ccn_node *CHKmonop(ccn_node *);
ccn_node *CPYbinop(ccn_node *);
ccn_node *DELbinop(ccn_node *);
ccn_node *CHKbinop(ccn_node *);
ccn_node *CPYassign(ccn_node *);
ccn_node *DELassign(ccn_node *);
ccn_node *CHKassign(ccn_node *);
ccn_node *CPYstmts(ccn_node *);
ccn_node *DELstmts(ccn_node *);
ccn_node *CHKstmts(ccn_node *);
ccn_node *CPYvardecl(ccn_node *);
ccn_node *DELvardecl(ccn_node *);
ccn_node *CHKvardecl(ccn_node *);
ccn_node *CPYparam(ccn_node *);
ccn_node *DELparam(ccn_node *);
ccn_node *CHKparam(ccn_node *);
ccn_node *CPYglobdef(ccn_node *);
ccn_node *DELglobdef(ccn_node *);
ccn_node *CHKglobdef(ccn_node *);
ccn_node *CPYglobdecl(ccn_node *);
ccn_node *DELglobdecl(ccn_node *);
ccn_node *CHKglobdecl(ccn_node *);
ccn_node *CPYfor(ccn_node *);
ccn_node *DELfor(ccn_node *);
ccn_node *CHKfor(ccn_node *);
ccn_node *CPYdowhile(ccn_node *);
ccn_node *DELdowhile(ccn_node *);
ccn_node *CHKdowhile(ccn_node *);
ccn_node *CPYwhile(ccn_node *);
ccn_node *DELwhile(ccn_node *);
ccn_node *CHKwhile(ccn_node *);
ccn_node *CPYifelse(ccn_node *);
ccn_node *DELifelse(ccn_node *);
ccn_node *CHKifelse(ccn_node *);
ccn_node *CPYfunbody(ccn_node *);
ccn_node *DELfunbody(ccn_node *);
ccn_node *CHKfunbody(ccn_node *);
ccn_node *CPYfundef(ccn_node *);
ccn_node *DELfundef(ccn_node *);
ccn_node *CHKfundef(ccn_node *);
ccn_node *CPYfundefs(ccn_node *);
ccn_node *DELfundefs(ccn_node *);
ccn_node *CHKfundefs(ccn_node *);
ccn_node *CPYcast(ccn_node *);
ccn_node *DELcast(ccn_node *);
ccn_node *CHKcast(ccn_node *);
ccn_node *CPYfuncall(ccn_node *);
ccn_node *DELfuncall(ccn_node *);
ccn_node *CHKfuncall(ccn_node *);
ccn_node *CPYreturn(ccn_node *);
ccn_node *DELreturn(ccn_node *);
ccn_node *CHKreturn(ccn_node *);
ccn_node *CPYexprstmt(ccn_node *);
ccn_node *DELexprstmt(ccn_node *);
ccn_node *CHKexprstmt(ccn_node *);
ccn_node *CPYids(ccn_node *);
ccn_node *DELids(ccn_node *);
ccn_node *CHKids(ccn_node *);
ccn_node *CPYarrexpr(ccn_node *);
ccn_node *DELarrexpr(ccn_node *);
ccn_node *CHKarrexpr(ccn_node *);
ccn_node *CPYexprs(ccn_node *);
ccn_node *DELexprs(ccn_node *);
ccn_node *CHKexprs(ccn_node *);
ccn_node *CPYdecls(ccn_node *);
ccn_node *DELdecls(ccn_node *);
ccn_node *CHKdecls(ccn_node *);
ccn_node *CPYprogram(ccn_node *);
ccn_node *DELprogram(ccn_node *);
ccn_node *CHKprogram(ccn_node *);
