#include "ccngen/actions.h"
#include "ccn/ccn_types.h"
#include "ccn/dynamic_core.h"
const ccn_trav_ft print_vtable[_NT_SIZE] = { &TRAVerror, &PRTbool, &PRTfloat, &PRTnum, &PRTvar, &PRTvarlet, &PRTmonop, &PRTbinop, &PRTassign, &PRTstmts, &PRTvardecl, &PRTparam, &PRTglobdef, &PRTglobdecl, &PRTfor, &PRTdowhile, &PRTwhile, &PRTifelse, &PRTfunbody, &PRTfundef, &PRTfundefs, &PRTcast, &PRTfuncall, &PRTreturn, &PRTexprstmt, &PRTids, &PRTarrexpr, &PRTexprs, &PRTdecls, &PRTprogram, };
const ccn_pass_ft ccn_pass_vtable[_PASS_SIZE] = { &PASSerror, &SPdoScanParse, };
const ccn_trav_ft ccn_copy_vtable[_NT_SIZE] = { &TRAVerror, &CPYbool, &CPYfloat, &CPYnum, &CPYvar, &CPYvarlet, &CPYmonop, &CPYbinop, &CPYassign, &CPYstmts, &CPYvardecl, &CPYparam, &CPYglobdef, &CPYglobdecl, &CPYfor, &CPYdowhile, &CPYwhile, &CPYifelse, &CPYfunbody, &CPYfundef, &CPYfundefs, &CPYcast, &CPYfuncall, &CPYreturn, &CPYexprstmt, &CPYids, &CPYarrexpr, &CPYexprs, &CPYdecls, &CPYprogram, };
const ccn_trav_ft ccn_check_vtable[_NT_SIZE] = { &TRAVerror, &CHKbool, &CHKfloat, &CHKnum, &CHKvar, &CHKvarlet, &CHKmonop, &CHKbinop, &CHKassign, &CHKstmts, &CHKvardecl, &CHKparam, &CHKglobdef, &CHKglobdecl, &CHKfor, &CHKdowhile, &CHKwhile, &CHKifelse, &CHKfunbody, &CHKfundef, &CHKfundefs, &CHKcast, &CHKfuncall, &CHKreturn, &CHKexprstmt, &CHKids, &CHKarrexpr, &CHKexprs, &CHKdecls, &CHKprogram, };
const ccn_trav_ft ccn_free_vtable[_NT_SIZE] = { &TRAVerror, &DELbool, &DELfloat, &DELnum, &DELvar, &DELvarlet, &DELmonop, &DELbinop, &DELassign, &DELstmts, &DELvardecl, &DELparam, &DELglobdef, &DELglobdecl, &DELfor, &DELdowhile, &DELwhile, &DELifelse, &DELfunbody, &DELfundef, &DELfundefs, &DELcast, &DELfuncall, &DELreturn, &DELexprstmt, &DELids, &DELarrexpr, &DELexprs, &DELdecls, &DELprogram, };
const ccn_trav_ft ccn_error_vtable[_NT_SIZE] = { &TRAVerror, &TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,&TRAVerror,};
const ccn_trav_ft *ccn_trav_vtable[_TRAV_SIZE] = { ccn_error_vtable, print_vtable, ccn_free_vtable, ccn_check_vtable, ccn_copy_vtable, };
const ccn_trav_data_ft trav_data_init_vtable[_TRAV_SIZE] = {TRAVdataNOP,TRAVdataNOP,TRAVdataNOP, TRAVdataNOP, TRAVdataNOP};
const ccn_trav_data_ft trav_data_free_vtable[_TRAV_SIZE] = {TRAVdataNOP,TRAVdataNOP,TRAVdataNOP, TRAVdataNOP, TRAVdataNOP};
